### ISSUE TITLE
npm install with node v4 and npm v3

### ISSUE THREAD

**Issue by VictorBjelkholm** [haadcode/orbit#105]
```
npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/home/victor/.nvm/versions/node/v4.2.6/bin/node" "/home/victor/.nvm/versions/node/v4.2.6/bin/npm" "install" "https://github.com/haadcode/go-ipfs-dep.git" "--verbose"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
```

Arguments and versions ^

Seems like it's not installing properly. Gist of error here: `Refusing to delete /home/victor/projects/misc/orbit/node_modules/go-ipfs-dep/node_modules/.bin/go-platform: containing path /home/victor/projects/misc/orbit/node_modules/go-ipfs-dep/node_modules/go-platform isn't under npm's control`

Full install log here: https://ipfs.io/ipfs/QmWLeofnwHG3nws99LFuprygFojpTUXQRuHjdiZEANSQz3

**Comment by haadcode** [comment]
Not sure why that is, never seen it before.

Also, please note that Orbit requires Node.js v6 as per requirements in README https://github.com/haadcode/orbit/tree/pubsub#requirements

**Comment by haadcode** [comment]
I'm gonna close this as it concerns Node.js v4. If you still run into build problem, please do open new issues.
