### ISSUE TITLE
File URLs are off

### ISSUE THREAD

**Issue by jbenet** [haadcode/orbit#11]
Looks like file gateway URLs are off (urls for files posted):
- now using: `http://localhost:5001/api/v0/cat?arg=QmZQhYyhYqwiBsyybyFP9VG1nFh6CMB8o3r5U8EMRagYT9` 
  - API and read-write (protected) port
- want: `http://localhost:8080/ipfs/QmZQhYyhYqwiBsyybyFP9VG1nFh6CMB8o3r5U8EMRagYT9` 
  - Gateway and read-only port

**Comment by haadcode** [comment]
This is fixed in master now.
