### ISSUE TITLE
go-ipfs floodsub1 requires ipfs daemon flag

### ISSUE THREAD

**Issue by jbenet** [haadcode/orbit#110]
@whyrusleeping asked me to say that: go-ipfs now ([floodsub1](https://dist.ipfs.io/go-ipfs/floodsub-1)) requires launching `ipfs daemon` with a flag to enable pubsub, like this:

```
ipfs daemon --enable-pubsub-experiment
```

I looked and https://github.com/ipfs/js-ipfsd-ctl didn't let you add flags, so i wrote https://github.com/ipfs/js-ipfsd-ctl/pull/107 to add flags. You should now be able to do:

```js
node = new ipfsdctl()
node.init(...)
node.startDaemon(['--enable-pubsub-experiment'], cb)
```

That PR also fixes some bugs in ipfsd-ctl, so it may work better now. It will report errors better if it fails to boot up the ipfs node (which previously were totally silent failures)

**Comment by haadcode** [comment]
Excellent! I'll pull that in. Thanks for adding the gatewayAddr also :+1:

**Comment by haadcode** [comment]
Fixed in branch `pubsub`.
