### ISSUE TITLE
Separate UI to its own project

### ISSUE THREAD

**Issue by haadcode** [haadcode/orbit#112]
The Electron app and browser UI should be separated to its own project and repository.

**Comment by r0kk3rz** [comment]
It would also be nice if the backend libraries didnt rely on anything with DOM or Node.js specific stuff.

This would allow the libraries to be used for a QML based client, which has its own javascript environment.

**Comment by haadcode** [comment]
@r0kk3rz have you come across this somewhere? I totally agree with what you're saying and would to know where it breaks atm so I can fix it. Let me know if there's anything specific that is not working.

**Comment by r0kk3rz** [comment]
@haadcode I haven't come across anything specific yet, but creating a QML client for orbit is something I would like to do. So its something to consider with any refactoring work you might be doing

**Comment by haadcode** [comment]
@r0kk3rz got it, thanks for the comments!

**Comment by haadcode** [comment]
This has been done. The code in this repo was finally split accordingly and can be found in the new location under github/orbitdb organization:
- [orbit-core](https://github.com/orbitdb/orbit-core) - Core Orbit library
- [orbit-web](https://github.com/orbitdb/orbit-web) - Orbit browser app
- [orbit-electron](https://github.com/orbitdb/orbit-electron) - Orbit desktop app

**Comment by haadcode** [comment]
@r0kkerz you should now be able to use orbit-core as a module to build new clients and programs for Orbit. Let me know if there's anything else we can do to help!
