### ISSUE TITLE
File a catch for npm3

### ISSUE THREAD

**Issue by RichardLitt** [haadcode/orbit#14]

**Comment by jbenet** [comment]
- @RichardLitt had npm 3 installed (as `npm`), but not `npm3` program
- gruntfile requires precisely the `npm3` program
- the error message is not clear, needs to be obvious to the user. something like:
  ```
  > grunt build
  ... stuff ...
  error: npm3 tool not found. 
  please install npm3 by running:  npm install npm3
  ```

that reminds me, lets make sure nothing requires `npm install -g` and it's all local (i.e. it puts the bins in `node_modules/.bin` and uses them from there. may need to add `node_modules/.bin` to `$PATH` in gruntfile, or hardcode it in the paths.

**Comment by haadcode** [comment]
Thanks for filing the issue! I'm working on to fix this and get rid of npm3 wrapper altogether.

**Comment by RichardLitt** [comment]
Sorry; I used `ghi` to quickly open this, was planning to fill it out later. Better to have it here than to forget to do it.

**Comment by haadcode** [comment]
This is fixed now.
