### ISSUE TITLE
Emoji auto complete and preview

### ISSUE THREAD

**Issue by haadcode** [haadcode/orbit#16]
When the user types `:`, an emoji preview should appear. The emoji preview displays all available emojis. 

The preview automatically updates the available emojis based on the user input:
`:` --> display all emojis
`:he` --> display all emojis starting with `he`
`:smile` --> display all emojis starting with `smile`

User should be able to press `tab` to cycle through the list of available emojis.
If the user cycles through the available emojis using tab, the emoji is select when user presses `space` or `return`. When an emoji is selected (after pressing `space` or `return`), the emoji preview should close.

The emoji preview should display the emoji picture only (no text). If the user cycles through the available emojis, the text in the input field should change to the select emojis, eg: `:hea` --> `press tab` --> input field should say: `:heart:`.

If the emoji preview is shown and the user presses `esc`, the emoji preview should close.

Extra: User should be able to select an emoji from the preview using `left arrow` and `right arrow`.

The emoji preview should be an absolutely positioned `<div>`. It should be located as close to the input text field as possible. However, it should not be *in* or *on* the input text field. The visual style should follow Orbit's general style.

**Comment by ralphtheninja** [comment]
+1

**Comment by shamb0t** [comment]
I can work on this
