### ISSUE TITLE
Make sure that two instances of the electron can run simultaneously

### ISSUE THREAD

**Issue by haadcode** [haadcode/orbit#167]
It should be possible to run two instances of the Orbit Electron app simultaneously. 

This may or may not be the case atm, so we need to make sure that this is possible.

**Comment by theobat** [comment]
I fired 2 versions on the same machine, **it seems fine until I press enter on the second username, it freezes**
I'm trying to troubleshoot what's going on in there

**Comment by haadcode** [comment]
@theobat Thanks for looking into this! I have an idea what's going on. Can you try the same but with the other daemon launched with `IPFS_PATH=/some/other/dir`? At the moment, if two instances are launched, they will both use the same IPFS data directory and I *think* this is what's causing the problems. 

As for this issue, we were discussing (offline) that we should provide a configuration screen when starting Orbit so that the user can define their custom IPFS data path if they wanted to, enabling two instances. See https://github.com/haadcode/orbit/issues/166.

Another thing I'd like to do is to namespace the data dirs per username, but that requires a bit more work https://github.com/haadcode/orbit/issues/163.

**Comment by theobat** [comment]
Yep, that fixed the problem, it's fine with n instances as long as they have different ipfs path. Now even if I implement  #166 I think it would be good to get a default path incrementing by default so that the user does not have to do it by himself, don't you think ?

**Comment by haadcode** [comment]
What do you mean by "default path incrementing"? Do you mean always using a unique path or something else?

**Comment by theobat** [comment]
I mean a unique path per electron instances which can be overridden by the user (with the ui of #166) (we don't need it to be unique at any run, a uuid would be overkill in my opinion)

**Comment by haadcode** [comment]
:+1:
