### ISSUE TITLE
Can't join a channel

### ISSUE THREAD

**Issue by shamb0t** [haadcode/orbit#17]
After connecting to the network, I can't seem to join a channel

Tried joining #ipfs and after the loading animation the page stays like this:
<img width="1322" alt="screen shot 2016-05-10 at 3 16 53 pm" src="https://cloud.githubusercontent.com/assets/2730657/15144785/afb8a8b0-16c2-11e6-8358-82ed791d8b39.png">

The channelstore isn't receiving any channels after the join:
<img width="983" alt="screen shot 2016-05-10 at 3 26 01 pm" src="https://cloud.githubusercontent.com/assets/2730657/15144834/fd98509e-16c2-11e6-9686-d8b436d3c2bf.png">

running ipfs 0.4.1
node v5.6.0
npm v3.6.0

**Comment by wanderer** [comment]
Also A problem for me

**Comment by jbenet** [comment]
@haadcode guessing this is resolved?

**Comment by haadcode** [comment]
Fixed in master.
