### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by haadcode** [haadcode/orbit#2]
Anonymous Networks was always a project name. "Anonymous" is misleading and causing confusion.

I'd like to rename the app to something better. Possibly with interplanetary inspiration behind the name :)

Suggestions welcome!

**Comment by haadcode** [comment]
"Anonymous" is misleading and causing confusion.

**Comment by jbenet** [comment]
some suggestions, but you should really pick whatever sings to you the most

- deck (deck of a ship)
- bridge (bridge of a ship)
- starchat 
- spacechat
- spacetalk
- startalk -- though clash http://www.startalkradio.net/
- ipc
- ipchat
- iptalk

**Comment by haadcode** [comment]
Are you guys fine if InterPlanetary is used in the name?

**Comment by jbenet** [comment]
yeah go for it, just ask before you select one as there may be some we're reserving-- though i might be tempted to use ipc or ipchat some day too. **shrug**

**Comment by mekarpeles** [comment]
Hale-baked ideas: (IPRC) InterPlanetary Relay Chat, (ICN) InterPlanetary Chat Network, the (ICE) InterPlanetary Chat Network, IM (InterPlanetary Messenger), (ICS) InterPlanetary Chat Stream, (IC) InterPlanetary Chat

**Comment by haadcode** [comment]
Trying out a new name, see master.
