### ISSUE TITLE
Planets missing in Electron

### ISSUE THREAD

**Issue by haadcode** [haadcode/orbit#204]
The little planets orbiting the rings in the Orbit logo don't appear in Electron. They appear when run in Chrome.

Need to investigate why.

@theobat FYI

**Comment by haadcode** [comment]
This is NOT an Electron bug. The planets go missing only when the theme !== 'Purple' so I think this is to due with the hue-rotation and/or the planets' color format. Need to investigate more.

**Comment by haadcode** [comment]
Found the planets!

**Comment by theobat** [comment]
Nice!
