### ISSUE TITLE
attaching files + drag and drop doesn't work in the browser version

### ISSUE THREAD

**Issue by diasdavid** [haadcode/orbit#212]
![image](https://cloud.githubusercontent.com/assets/1211152/21162552/db93fa86-c142-11e6-94a5-ac39f2d40c71.png)

**Comment by theobat** [comment]
@diasdavid perhaps you should move that to #210 ?

**Comment by haadcode** [comment]
Fixed in https://github.com/haadcode/orbit/pull/213
