### ISSUE TITLE
Using Morph.is code to improve Orbit

### ISSUE THREAD

**Issue by arkgit** [haadcode/orbit#218]
the main developer was shot and killed 2 weeks ago and it would mean alot for his work to live on. https://morph.is is a distributed datastore like IPFS and there was a ui being developed for a distributed irc which you can get if you pull the source and git checkout f-dds

 the distributed irc was almost done  heres a mockup of what it was going to look like https://ipfs.pics/Qmab8KzU4jCEYwwHQaDRNBQGu2eRSf9Qvkhfjn7Q63qFTH
if you run a morphis node with the f-dds branch you can see most of it in action. there were some tweaks to the ui we had talked about but never got around to finish.

Heres a backup of the code including all branches (which is also currently still available on the official morph.is git repo until the servers go offline)

https://u.teknik.io/XWzPR.zip

**Comment by haadcode** [comment]
@arkgit I'm really, really sorry to hear that :( That's horrible and I don't know what to say except my deepest condolences.

I can take a look at the f-dds code base and see what's there and how it would fit together with Orbit and IPFS. It'll take me sometime though as I'm completely booked the next two weeks.

Who were the main developers of that (f-dds, distributed IRC) project? Are there people who would be interested to continue that work either as a separate project or eg. part of other project, like Orbit?

**Comment by arkgit** [comment]
it was pretty much only him on the code, and his common law wife on the ui.
i think someone (fps i think) on the #morphis irc on freenode might have
done a push request or two. i helped on bug reporting and ui tips

**Comment by haadcode** [comment]
@arkgit I took a look at the code, but I don't see a clear way to use it and given the potential licensing issues, I'm afraid we can't fulfil your request here. 

Once again, sorry to hear about the loss and hopefully the code will live on in some other way. Let me know if there's more to discuss, feel free to re-open this issue and I'd be happy to provide input.

Closing the issue.
