### ISSUE TITLE
Settings - Theme: [object Object]

### ISSUE THREAD

**Issue by dignifiedquire** [haadcode/orbit#22]
Opening the settings panel shows this: 

![screen shot 2016-05-19 at 11 18 00](https://cloud.githubusercontent.com/assets/790842/15388680/622e49c2-1db3-11e6-9c81-e780f968d365.png)

**Comment by dignifiedquire** [comment]
Also there is no save, cancel or close button to get back from the settings

**Comment by haadcode** [comment]
This was fixed by @jihdeh in https://github.com/haadcode/orbit/pull/156
