### ISSUE TITLE
Messages with the same content have different hashes

### ISSUE THREAD

**Issue by shamb0t** [haadcode/orbit#228]
Should messages with the same content have different hashes? 
<img width="1312" alt="screen shot 2017-02-02 at 2 56 27 pm" src="https://cloud.githubusercontent.com/assets/2730657/22548538/40b42770-e960-11e6-85bc-093e043cd548.png">

**Comment by haadcode** [comment]
> Should messages with the same content have different hashes?

They should. Why the hash is different is that each message also contains a timestamp, so, posted at different times, different hashes.
