### ISSUE TITLE
maybe rename Anonymous?

### ISSUE THREAD

**Issue by jbenet** [haadcode/orbit#3]
Anonymity in crypto and messaging tools tends to mean privacy + untraceability, so things like tor and i2p. ip addresses of requesting things could be enough. i'd recommend renaming altogether. as i've mentioned this app to others their immediate questions lead down the tor/i2p route.

**Comment by haadcode** [comment]
This is consistent with the feedback I've received so far and I'm planning on changing the name at some point. See https://github.com/haadcode/anonymous-networks/issues/2 and pitch in for ideas! :)
