### ISSUE TITLE
Issue collection

### ISSUE THREAD

**Issue by dignifiedquire** [haadcode/orbit#33]
I'm collecting all errors I see while running it in here so we have a place to find them

![screen shot 2016-06-01 at 14 14 21](https://cloud.githubusercontent.com/assets/790842/15709879/6e205f46-2807-11e6-9091-fd78b9103abd.png)
![screen shot 2016-06-01 at 14 44 06](https://cloud.githubusercontent.com/assets/790842/15709881/6fc4d714-2807-11e6-992f-a3383fbc7380.png)

![screen shot 2016-06-01 at 14 45 43](https://cloud.githubusercontent.com/assets/790842/15709895/8989caec-2807-11e6-916b-bac7656e3931.png)

Also: https://github.com/diasdavid/js-libp2p-swarm/issues/75

**Comment by haadcode** [comment]
<img width="818" alt="screen shot 2016-06-03 at 16 03 59" src="https://cloud.githubusercontent.com/assets/7499694/15781121/ec9ff248-29a4-11e6-89bf-03309e81817d.png">

**Comment by haadcode** [comment]
This is the sequence of errors that happens on timeout:
![screen shot 2016-06-06 at 09 14 24](https://cloud.githubusercontent.com/assets/7499694/15814488/317a2658-2bc7-11e6-83ac-dd98c6f27575.png)

**Comment by haadcode** [comment]
Closing this as most of these issues have been fixed in js-ipfs and libp2p. For further issues, let's track them individually at their respective repositories.
