### ISSUE TITLE
Fix file previews

### ISSUE THREAD

**Issue by haadcode** [haadcode/orbit#40]

**Comment by haadcode** [comment]
Blocked by https://github.com/ipfs/js-ipfs-api/issues/323

**Comment by diasdavid** [comment]
Blocked as in "you need to use 0.4.3"? Once the release is done and this fixed, the migration should be seamless to you. This is a very important bug to fix soon nevertheless, but let me know what you need so we can bump it even more :)

**Comment by diasdavid** [comment]
Blocked as in "you need to use 0.4.3"? Once the release is done and this fixed, the migration should be seamless to you. This is a very important bug to fix soon nevertheless, but let me know what you need so we can bump it even more :)
