### ISSUE TITLE
Reduce Electron app's startup time

### ISSUE THREAD

**Issue by haadcode** [haadcode/orbit#55]
Currently, the Electron app's initial startup time can take anything from a couple of seconds to ten. This is due to booting up the go-ipfs daemon first and only then displaying the "login" screen.

To fix this, we should display index.html immediately and start go-ipfs daemon after that (or in parallel). We should also display a "Loading..." text while loading in more assets or starting ipfs daemon.

**Comment by dignifiedquire** [comment]
Suggestion: Display something like `Starting ipfs` while the node is starting up.

**Comment by haadcode** [comment]
This is being worked on as part of #166. cc @theobat.

**Comment by haadcode** [comment]
This has been achieved. The startup time was massively reduced with the new startup sequence made by @theobat. We now first load the UI, ask for credentials and only after then we start the IPFS daemon.

This can be further reduced in go-ipfs (iiuc from @whyrusleeping and @jbenet) by boostrapping ipfs after starting the daemon (in go-ipfs), so hopefully in the future we have something instant for the startup sequence. It's not bad today either, feels very snappy :)

Good work everyone involved!
