### ISSUE TITLE
use different ipfs repos

### ISSUE THREAD

**Issue by jbenet** [haadcode/orbit#6]
### background

It seems to me (sorry need to do more digging, will get to it later if i can) orbit asumes the ipfs repo is in `~/.ipfs` always. this makes it a bit difficult when playing with repos of different versions (eg fs-repo@1 (go-ipfs@0.3.x) and fs-repo@2 (go-ipfs@0.4.x)

### requests

would be nice if orbit:
- maybe default to a different location?
- allows specifying the path to the repo as part of the running cmd. `node index.js --repo <repo-path>`
- maybe supported `IPFS_PATH` (go-ipfs does) -- env vars have no place in apps. but maybe for development its ok. not sure.
- or maybe keep it in orbit-db-cache.json ? not sure, likely doesnt belong there.

sorry, i need to understand the internals better to provide good suggestions. maybe @diasdavid has better thoughts

**Comment by diasdavid** [comment]
We can have IPFS_PATH for dev, but also have a settings page (for UX) to config the location of the IPFS Repo, such that if it doesn't find one on the default path, it will prompt the user, or if it finds, the users will be able change on the settings screen.

**Comment by haadcode** [comment]
`IPFS_PATH` is supported by ipfsd-ctl and now by Orbit. Fix still in a branch but fixed.

**Comment by haadcode** [comment]
This should now be possible with `IPFS_PATH`. Fixed in master.

**Comment by jbenet** [comment]
+1 to @diasdavid's suggestion that there should be a way to configure this
in the UI itself? but prob not worth doing for a while

**Comment by haadcode** [comment]
I don't think Orbit's settings are the right place to do such config. From user's perspective, well, they don't care where the repo is, or what a repo even is. To me this sounds purely a dev feature. Let me know if you disagree, though.
