### ISSUE TITLE
Cleaner local state when running the app

### ISSUE THREAD

**Issue by jbenet** [haadcode/orbit#7]
right now running orbit locally ( `node index.js`) uses some local state in its home directory. its not clear what is "dirty" and can be removed. (its not super clear from the gitignore either)

it may be better to have either:
- a clear account of what those files are in the readme, (or via `clean` target in a `Makefile` /  `Gruntfile`) 
- or put all those under a directory, like `orbit-data` or something.

**Comment by haadcode** [comment]
This should be fixed now in the pubsub branch. I'm gonna keep this open until the changes are in master but do let me know if you still find issues with the dev directory state.
