### ISSUE TITLE
Reduce client's build time

### ISSUE THREAD

**Issue by haadcode** [haadcode/orbit#74]
Rebuilding the client build in development (`grunt serve`) takes painfully long. We need to reduce this as much as possible to improve the developer experience.

**Comment by haadcode** [comment]
First part is done: https://github.com/haadcode/orbit/commit/abbdf67c3c52e7ddf96d516904b518f5d54c8483

js-ipfs is still bundled with the app code due to it being included in webpack exports. We should change the loading of ipfs module so that it happens in index.html (load it from cdn/static asset/url/window.Ipfs) and main.js doesn't require() it.

**Comment by diasdavid** [comment]
With every js-ipfs release, a dist is created and put on npmcdn. You can use that one already :)

**Comment by haadcode** [comment]
I prefer to have all assets included with the build, less stuff to download the better :) But essentially that's what I ended up doing with js-ipfs for now, I couldn't get it chunked in webpack :/

**Comment by haadcode** [comment]
This was improved greatly with Webpack 2. I think it's ok atm. If we still want to make it faster, let's re-open this issue then.
