### ISSUE TITLE
Bad failure when opening Orbit.app with repo of wrong version

### ISSUE THREAD

**Issue by jbenet** [haadcode/orbit#98]
This shows up when opening Orbit.app with an ipfs repo of unexpected version (`4` instead of `3`). Seems like a check for expected repo version should happen, and a clear error message given to the user.

![orbit-ver-err-1](https://cloud.githubusercontent.com/assets/138401/18251944/88140b66-738c-11e6-83ec-2963b59f54a3.png)
![orbit-ver-err-2](https://cloud.githubusercontent.com/assets/138401/18251943/880fc0e2-738c-11e6-846b-991dca598920.png)

**Comment by haadcode** [comment]
This should be fixed in pubsub branch now.
