### ISSUE TITLE
Requires pre-inited .ipfs repo

### ISSUE THREAD

**Issue by jbenet** [haadcode/orbit#99]
Starting a pre-built Orbit.app fails cryptically with the following errors. It seems that it requires:
- an existing ipfs repo to exist in `~/.ipfs`

![orbit-errs](https://cloud.githubusercontent.com/assets/138401/18251959/9f784c0e-738c-11e6-8a84-43fd4061c117.png)

**Comment by haadcode** [comment]
This shouldn't be case anymore, fixed in pubsub branch.
